added support of mixed chinese and english
rainzm/flash-zh.nvim pull request #4
Opened 2024-04-03 14:30 UTC by dirichy

2024-04-03 15:34 UTC, rainzm commented
WOW，非常感谢你的PR，我仔细地阅读了，我觉得是一个非常好的完善，然后我有些想法和你沟通：

2024-04-03 15:43 UTC, rainzm requested changes
WOW，非常感谢你的PR，我仔细地阅读了，我觉得是一个非常好的完善，然后上面是我的一些想法。

2024-04-03 15:43 UTC, rainzm commented on lua/flash-zh/init.lua
> +	singlepin = function(str)
我觉得singlepin的定义应该是不包含alpha的，所以char1patterns中的alpha部分应该去掉，和char2patterns保持一致。

2024-04-03 15:43 UTC, rainzm commented on lua/flash-zh/init.lua
> +			prefix[#prefix + 1] = { str = firstchar, type = "singlepin" }
基于singlepin不包含alpha的情况，这里应该分类：
```lua
local prefix2 = M.copy(prefix)
prefix[#prefix + 1] = { str = firstchar, type = "alpha" }
prefix2[#prefix2 + 1] = { str = firstchar, type = "singlepin" }
return { prefix, prefix2 }
```

2024-04-03 15:43 UTC, rainzm commented on lua/flash-zh/init.lua
> +				prefix[#prefix + 1] = { str = firstchar, type = "singlepin" }
当firstchar以及secondchar均为字母，且两者无法构成拼音时候，firstchar一定是个alpha，而不会是singleping。

2024-04-03 17:27 UTC, dirichy commented on lua/flash-zh/init.lua
> +				prefix[#prefix + 1] = { str = firstchar, type = "singlepin" }
是的，我写的时候没有注意，这里确实可以去掉字母的部分。我第一次写插件，可能写的会有一些问题，代码命名什么的也比较乱来，谢谢你指出问题。

2024-04-03 19:17 UTC, dirichy commented
我已经修改并且在本地简单测试过了，我是第一次发pr所以不太清楚接下来我该怎么操作才能把新代码更新到这个pr。

此外我发现我这种迭代的方案导致当字符串长度过长（在我的电脑中长度超过6）时卡顿会比较明显，甚至卡到动不了，不知道有没有什么解决方法

2024-04-04 03:45 UTC, rainzm commented
> 我已经修改并且在本地简单测试过了，我是第一次发pr所以不太清楚接下来我该怎么操作才能把新代码更新到这个pr。

应该只要继续加commit到你的提PR的source分支中就好了。

> 此外我发现我这种迭代的方案导致当字符串长度过长（在我的电脑中长度超过6）时卡顿会比较明显，甚至卡到动不了，不知道有没有什么解决方法

实际使用中会有这么长的匹配情况嘛，感觉一般最多2-3个字符就能使得匹配项有label了吧，你有6个字符的例子嘛？

2024-04-04 06:06 UTC, merged

2024-04-04 11:35 UTC, dirichy commented
确实大部分情况下是没有问题的，这样应该可以了我觉得

2024-04-04 14:03 UTC, rainzm commented
OK，我合并之后又做了点修改，主要是保留了之前chinese_only的模式，分开了singlepin和comma，comma里面加了 `"` 的匹配项目。